#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: Lint Markdown Files

# https://github.com/reviewdog/action-markdownlint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          filter_mode: added
          fail_on_error: false
          ### Flags for markdownlint-cli ###
          # markdownlint_flags: .
